### ISSUE TITLE
Customizable entries

### ISSUE THREAD

**Issue by jsildatk** [Taskyers/tasky-ui#55]

**Comment by Marynx** [comment]
- GET, /secure/projects/settings/entries/{projectName}/{type} - to get list of project's entries of given type

-  GET, /secure/projects/settings/entries/{projectName}/{value}/{type} - to get boolean if value with given entry type already exists in this project - for validation

- POST, /secure/projects/settings/entries/{projectName} - to add new entry entity, JSON with {value, textColor, backgroundColor,entryType} colors in hex if possible with color pickers

- PUT, /secure/projects/settings/entries/{id} - to edit entry entity, same JSON as above

- DELETE, /secure/projects/settings/entries/{id} - to delete entry entity
